const PLAY_ALARM_SOUND = "PLAY_ALARM_SOUND";

const PLAY_BUTTON_SOUND = "PLAY_BUTTON_SOUND";

const SET_POMO_TIMER = "SET_POMO_TIMER";

export const MAIN_MESSAGE = {
  PLAY_ALARM_SOUND,
  PLAY_BUTTON_SOUND,
  SET_POMO_TIMER,
} as const;
