const FINISH_SLOT = "FINISH_SLOT";

const GET_POMO_TIMER = "GET_POMO_TIMER";

const RESET_COUNT = "RESET_COUNT";

const RESET_SETTING = "RESET_SETTING";

const RESET_TIMER = "RESET_TIMER";

const START_TIMER = "START_TIMER";

const STOP_TIMER = "STOP_TIMER";

const SWITCH_SLOT = "SWITCH_SLOT";

const UPDATE_ALARM_NAME = "UPDATE_ALARM_NAME";

const UPDATE_ALARM_REPEAT = "UPDATE_ALARM_REPEAT";

const UPDATE_ALARM_VOLUME = "UPDATE_ALARM_VOLUME";

const UPDATE_AUTO_START_BREAK = "UPDATE_AUTO_START_BREAK";

const UPDATE_AUTO_START_POMODORO = "UPDATE_AUTO_START_POMODORO";

const UPDATE_DURATION = "UPDATE_DURATION";

const UPDATE_LONG_BREAK_INTERVAL = "UPDATE_LONG_BREAK_INTERVAL";

const UPDATE_RESET_TIME = "UPDATE_RESET_TIME";

const UPDATE_THEME = "UPDATE_THEME";

export const WORKER_MESSAGE = {
  FINISH_SLOT,
  GET_POMO_TIMER,
  RESET_COUNT,
  RESET_SETTING,
  RESET_TIMER,
  START_TIMER,
  STOP_TIMER,
  SWITCH_SLOT,
  UPDATE_ALARM_NAME,
  UPDATE_ALARM_REPEAT,
  UPDATE_ALARM_VOLUME,
  UPDATE_AUTO_START_BREAK,
  UPDATE_AUTO_START_POMODORO,
  UPDATE_DURATION,
  UPDATE_LONG_BREAK_INTERVAL,
  UPDATE_RESET_TIME,
  UPDATE_THEME,
} as const;
