import { z } from "zod/v4-mini";
import { WORKER_MESSAGE } from "../constants/workerMessage";
import {
  ALARM_NAME_SCHEMA,
  ALARM_REPEAT_SCHEMA,
  ALARM_VOLUME_SCHEMA,
  AUTO_START_BREAK_SCHEMA,
  AUTO_START_POMODORO_SCHEMA,
  COLOR_SCHEMA,
  LONG_BREAK_INTERVAL_SCHEMA,
  RESET_TIME_SCHEMA,
  SLOT_SCHEMA,
  TIME_SCHEMA,
} from "./pomoTimer";

const FINISH_SLOT_MESSAGE_SCHEMA = z.object({
  type: z.literal(WORKER_MESSAGE.FINISH_SLOT),
});

const GET_POMO_TIMER_MESSAGE_SCHEMA = z.object({
  type: z.literal(WORKER_MESSAGE.GET_POMO_TIMER),
});

const RESET_COUNT_MESSAGE_SCHEMA = z.object({
  type: z.literal(WORKER_MESSAGE.RESET_COUNT),
});

const RESET_SETTING_MESSAGE_SCHEMA = z.object({
  type: z.literal(WORKER_MESSAGE.RESET_SETTING),
});

const RESET_TIMER_MESSAGE_SCHEMA = z.object({
  type: z.literal(WORKER_MESSAGE.RESET_TIMER),
});

const START_TIMER_MESSAGE_SCHEMA = z.object({
  type: z.literal(WORKER_MESSAGE.START_TIMER),
});

const STOP_TIMER_MESSAGE_SCHEMA = z.object({
  type: z.literal(WORKER_MESSAGE.STOP_TIMER),
});

const SWITCH_SLOT_MESSAGE_SCHEMA = z.object({
  type: z.literal(WORKER_MESSAGE.SWITCH_SLOT),
  slot: SLOT_SCHEMA,
});

const UPDATE_ALARM_NAME_MESSAGE_SCHEMA = z.object({
  type: z.literal(WORKER_MESSAGE.UPDATE_ALARM_NAME),
  name: ALARM_NAME_SCHEMA,
});

const UPDATE_ALARM_REPEAT_MESSAGE_SCHEMA = z.object({
  type: z.literal(WORKER_MESSAGE.UPDATE_ALARM_REPEAT),
  repeat: ALARM_REPEAT_SCHEMA,
});

const UPDATE_ALARM_VOLUME_MESSAGE_SCHEMA = z.object({
  type: z.literal(WORKER_MESSAGE.UPDATE_ALARM_VOLUME),
  volume: ALARM_VOLUME_SCHEMA,
});

const UPDATE_AUTO_START_BREAK_MESSAGE_SCHEMA = z.object({
  type: z.literal(WORKER_MESSAGE.UPDATE_AUTO_START_BREAK),
  autoStartBreak: AUTO_START_BREAK_SCHEMA,
});

const UPDATE_AUTO_START_POMODORO_MESSAGE_SCHEMA = z.object({
  type: z.literal(WORKER_MESSAGE.UPDATE_AUTO_START_POMODORO),
  autoStartPomodoro: AUTO_START_POMODORO_SCHEMA,
});

const UPDATE_DURATION_MESSAGE_SCHEMA = z.object({
  type: z.literal(WORKER_MESSAGE.UPDATE_DURATION),
  key: SLOT_SCHEMA,
  value: TIME_SCHEMA,
});

const UPDATE_LONG_BREAK_INTERVAL_MESSAGE_SCHEMA = z.object({
  type: z.literal(WORKER_MESSAGE.UPDATE_LONG_BREAK_INTERVAL),
  longBreakInterval: LONG_BREAK_INTERVAL_SCHEMA,
});

const UPDATE_RESET_TIME_MESSAGE_SCHEMA = z.object({
  type: z.literal(WORKER_MESSAGE.UPDATE_RESET_TIME),
  resetTime: RESET_TIME_SCHEMA,
});

const UPDATE_THEME_MESSAGE_SCHEMA = z.object({
  type: z.literal(WORKER_MESSAGE.UPDATE_THEME),
  key: SLOT_SCHEMA,
  value: COLOR_SCHEMA,
});

export const WORKER_MESSAGE_SCHEMA = z.discriminatedUnion("type", [
  FINISH_SLOT_MESSAGE_SCHEMA,
  GET_POMO_TIMER_MESSAGE_SCHEMA,
  RESET_COUNT_MESSAGE_SCHEMA,
  RESET_SETTING_MESSAGE_SCHEMA,
  RESET_TIMER_MESSAGE_SCHEMA,
  START_TIMER_MESSAGE_SCHEMA,
  STOP_TIMER_MESSAGE_SCHEMA,
  SWITCH_SLOT_MESSAGE_SCHEMA,
  UPDATE_ALARM_NAME_MESSAGE_SCHEMA,
  UPDATE_ALARM_REPEAT_MESSAGE_SCHEMA,
  UPDATE_ALARM_VOLUME_MESSAGE_SCHEMA,
  UPDATE_AUTO_START_BREAK_MESSAGE_SCHEMA,
  UPDATE_AUTO_START_POMODORO_MESSAGE_SCHEMA,
  UPDATE_DURATION_MESSAGE_SCHEMA,
  UPDATE_LONG_BREAK_INTERVAL_MESSAGE_SCHEMA,
  UPDATE_RESET_TIME_MESSAGE_SCHEMA,
  UPDATE_THEME_MESSAGE_SCHEMA,
]);
